### ISSUE TITLE
Parvula CMS: How to create sub-pages and display in the navigation

### ISSUE THREAD

**Issue by AlexL777** [BafS/parvula#11]
Hello Developers,

I have now for the first time the parvula CMS discovered for myself and want to work with it a bit. I have everything installed and adds new pages.

Even I have allows Disqus comments, but a question I have currently and that there is a way to create sub-pages and to display in the header navigation in dropdown menu?

I would namely like to create more sub-pages and do not want all squeeze into the navigation. How best to do that?

Thanks in advance and great flat file CMS :smile:

**Comment by BafS** [comment]
Hi,

For the moment there is nothing bult-in into Parvula but sub-menu pages will be possible easily accessible in the next release (coming up really soon) !

Danke for your feedback.

**Comment by AlexL777** [comment]
OK thank you. Then I am patient and wait.

**Comment by BafS** [comment]
This feature is available in the new release !
There is an example right after the installation (check the page *Parent page*).
