### ISSUE TITLE
Are these features already in Parvula?

### ISSUE THREAD

**Issue by tyeeman** [BafS/parvula#12]
Great work, I will try the new version this week. Just wondering if there is a blog page function available. Most sites now have pages and posts (blog). If Parvula could add a blog menu item that would be great. When we click the blog menu item we should get a summary of the latest posts ( the number settable in the config). The summary page should consist of two sentences of each post with a "Read More" link underneath each one or being able to just click the title and be directed there. Being also able to add meta data of a "category" would be nice so a list of categories on one side of the page would take us to that specific category of blog posts.
These are just suggestions to make Parvula the best markdown fast cms out there. Keep up the good work Fabien!

**Comment by BafS** [comment]
Thank you for the feedback, I appreciate.
I was working on the blog part since yesterday, I've push an example on the 'dev' branch and this branch should be merged in the master really soon. I will try to do more little iterations for the next releases than before.

**Comment by BafS** [comment]
The new release has a blog layout.
