### ISSUE TITLE
Trying 0.6 - error

### ISSUE THREAD

**Issue by tyeeman** [BafS/parvula#14]
Just trying new version and got this error right away - 

````
0 Whoops\Exception\ErrorException
…\vendor\erusev\parsedown-extra\ParsedownExtra.php, line 468
Call to undefined function mb_convert_encoding()
````

**Comment by BafS** [comment]
With a fresh install but I do not have this error. Parsedown extra uses `mb_convert_encoding` so it needs the (Multibyte String)[https://secure.php.net/manual/en/book.mbstring.php] module.
I recommend you to install this module if possible.

**Comment by tyeeman** [comment]
OK, thanks. Maybe you can help me with a problem. In the last 2 days I can't get my Apache server running properly in Windows. I use Uwamp and when I click start button to start Apache it tries, then stops. If I run httpd.exe manually from a command window Apache starts fine. This is Windows 7 so there are no file perimissions like unix. I'm sure that's why I have this problem with parvula also. I'm still working on it.

**Comment by BafS** [comment]
For your problem it's hard to know like that and I am not on windows but I used to use [Wamp](http://www.wampserver.com/en/) and it worked really well.

To activate the Multibyte String module you need to open your `php.ini` file and uncomment (by removing the first `;`) the line `;extension=php_mbstring.dll` (don't forget to restart Apache).

**Comment by tyeeman** [comment]
Problem is I have multiple php installs in my windows computer, ie. mulitple php.ini files. Because the Uwamp server won't start now this problem occurs. If it did start everything would be ok. So I will try to find out what's wrong but they developer is not replying to my emails or superuser forum questions.

**Comment by tyeeman** [comment]
OK, thanks to stackoverflow I got Uwamp fixed and working. Just clicking around the Parvula package seems to work ok except when I click admin, I get the following error - 

````
 Whoops \ Exception \ ErrorException (E_ERROR)

Call to undefined method Slim\Container::getPluginPath() 
````
line 15 is this - 

````
'pluginUrl' => Parvula::getRelativeURIToRoot() . $this->getPluginPath(),
````
Any thoughts?

**Comment by BafS** [comment]
Thank you, it was a bug, sorry.
I have published a patch, you can run the command again to install the last version (0.6.1).
`composer create-project bafs/parvula cms`

**Comment by tyeeman** [comment]
Just tried installing new version and get this error - 

```
[RuntimeException]
The openssl extension is required for SSL/TLS protection but is not available. If you can not e
nable the openssl extension, you can disable this error, at your own risk, by setting the 'disa
ble-tls' option to true.
````

**Comment by BafS** [comment]
This exception is not from Parvula but Composer. 
Composer uses SSL/TLS to download files from the github repository.
I recommend that you activate the `php_openssl` in your php.ini (uncomment `;extension=php_openssl.dll`).
You can also [disable TLS](https://getcomposer.org/doc/06-config.md#disable-tls) `composer config -g -- disable-tls true` and then re-run the command.

**Comment by tyeeman** [comment]
Tried that now this error - 
````
g:\Tonys Appz\Uwamp\www\parvula>php "G:\Tonys Appz\composer\composer.phar" create-project bafs/parvu
la cms
You are running Composer with SSL/TLS protection disabled.
Your configuration does not allow connection to http://packagist.org. See https://getcomposer.org/do
c/06-config.md#secure-http for details.
http://packagist.org could not be fully loaded, package information was loaded from the local cache
and may be out of date


  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/bafs/parvula%244db1dc800526b77a514cc29e8a23c5773d93aed2194fc19cc3b4
  83ea4074c828.json" file could not be downloaded: failed to open stream: An attempt was made to
  access a socket in a way forbidden by its access permissions.
````

**Comment by tyeeman** [comment]
Finally got it installed.

**Comment by BafS** [comment]
Happy to hear that ! 
For `file could not be downloaded` it can be your php.ini or windows, what was it ? I have the impression that your php configuration is really restrictive but it seems to work now, I hope you will not have other issues.

**Comment by tyeeman** [comment]
Composer was trying to use the php version within Uwamp, so I switched it to use the installed version in Windows which worked. I don't know why the Uwamp version will not work. A setting is wrong somewhere but I spent too long trying to find it.

**Comment by BafS** [comment]
Okay.
In fact there is two way to install Parvula.
 1. You can download the sources (the zip from Github) and the run `composer install`.
 2. You can also simply do `composer create-project bafs/parvula cms`, it will download the sources and then, internally, do a `composer install`, so it's just a bit more quick.
