### ISSUE TITLE
How remove index.php in url ?

### ISSUE THREAD

**Issue by nibreh** [BafS/parvula#3]
Hi

I installed Parvula in a sub directory of my web hosting  
I can access pages and admin only if _index.php_ is in the URL

Example :

mysite.com/parvula/index.php/page __it's working__  
mysite.com/parvula/page __give me : No input file specified__  
mysite.com/parvula/ __Home page is Ok__

thanks - great app !

**Comment by BafS** [comment]
Hello,

Thanks for the feedback.
It is probably a problem with url rewriting. Do you use apache ? You need to have "*mod_rewrite.so*" loaded to rewrite urls. Edit your *httpd.conf* to enable this module.

**Comment by nibreh** [comment]
Mod rewrite is enable. My web hosting (legtux.org) use apache 2.2 & PHP 5.4 

By the way I fix it : 
In __.htacess__, changing
_RewriteRule ^(.*)$ index.php/$1 [L]_
TO
_RewriteRule . index.php [L]_

and it's working fine !
But I don't know why, I don't really understand :)

**Comment by BafS** [comment]
Interesting, I will check that.

Content que ça marche quand même !

**Comment by nibreh** [comment]
Tout à fait :)

**Comment by BafS** [comment]
This should be fixed in the current dev branch (see ec6d327). Next version will be released soon.

**Comment by BafS** [comment]
This is fixed in the new version. Please feel free to reopen the issue in case.
