### ISSUE TITLE
article tag in templates/fullpage/index.html

### ISSUE THREAD

**Issue by nibreh** [BafS/parvula#4]
There is a end _article_ tag in [templates/fullpage/index.html](https://github.com/BafS/parvula/blob/master/templates/fullpage/index.html) on line 54

**Comment by BafS** [comment]
Fixed, thanks ! 
https://github.com/BafS/parvula/blob/3b6ad0a2ee2c43a8f83cf70f848a15283076b43c/templates/fullpage/index.html
