### ISSUE TITLE
Admin Folder name change

### ISSUE THREAD

**Issue by tyeeman** [BafS/parvula#5]
Hi Fabien
   I was trying this code - 

    // Administration URL (/parvula-admin by default)
    'adminURL' => 'parvula-admin',

    // /adminFolderName (/admin by default) will redirect you to administration
    'adminAliasFolder' => true

The adminURL change works great but I don't understand the "adminAliasFolder = true" meaning? I thought I could rename the admin folder here to something else? What does true mean?

**Comment by BafS** [comment]
Sorry, it's not very clear.
In parvula you have the "admin" folder, when you go to "/admin" you can choose tu be redirected to the administration (as well as "/parvula-admin"), this is the alias.

I hope it's more understandable, if not, don't hesitate to ask.

**Comment by tyeeman** [comment]
Sorry for the delay getting back to this. So if "'adminAliasFolder' => false" what happens?

**Comment by BafS** [comment]
If it's false you can access administration via "/parvula-admin" but if you use the folder name (/admin) it will be forbidden.
Technical point: Because for urls, Parvula use the router but if the folder name exist (here /admin) apache will use the folder name and bypass the router.

**Comment by BafS** [comment]
In the next release administration will be a plugin and the path customizable easily.
