### ISSUE TITLE
Administration panel results in 404

### ISSUE THREAD

**Issue by yckart** [BafS/parvula#6]
It seems that there's something wrong with url rewriting. Visiting `/parvula-admin/` ends with a *unstyled* 404, `/parvula-admin` ends with a *styled* 404. `/admin` just shows a blank page.

Setting `RewriteBase /` in `.htaccess` doesn't help. It seems that there's something wrong with the routing.

**Comment by BafS** [comment]
In the next release administration will be a plugin and this bug has been finally fixed.
