### ISSUE TITLE
New dev version

### ISSUE THREAD

**Issue by tyeeman** [BafS/parvula#8]
Greetings
  I see you are working on a new dev version, excellent. I would like to kindly ask for a feature if possible. Nearly every markdown cms has one problem - only one content area. I did find one that has unlimited content areas due to it using twig for templating but I'm not asking for that here. 

I propose to add multiple content areas the following way - 

1. In the html template use $contentX for any content area, where X is a number starting at 1. Place all these in your desired template in the specific div you want for that content.

2. In the markdown, place ````<hr>```` between each content area and program the cms to seach for ````<hr>```` and when it finds that start creating each content area. For example at the top of the markdown file under the meta data place ````<hr>```` in it's own line. Under that type your markdown content for $content1. Place another ````<hr>```` under that in it's own line, then under that type your content for $content2, etc. 

Example
````
{{author:Me}}  
{{title:index}}  

<hr>

This is content1 markdown until the next hard return.

<hr>

This is content2 markdown
````

````<hr>```` does not have to be used, just something unique to separate the content areas.
What do you think? Pretty simple. This is how twig templates do it but we don't need to use them, just code the php to do the above!

**Comment by BafS** [comment]
I have implemented multiple contents, called "sections". Here an example:

```markdown
---
title: A page
---

# Main Content
...

---
mySection
---

# Section content
```

and *mySection* can be used in a theme file (`<?= $page->sections->mySection ?>`).

I will add some documentation soon, before the next release.

**Comment by tyeeman** [comment]
Nice, thanks!
